Fix outdated applio info
AIHubCentral/docs pull request #3
Opened 2024-04-20 00:39 UTC by aitronssesin

In this second pull request, I have replaced all the subjective elements and reviewed the grammar and vocabulary. For instance, I have made the following changes from the previous pull request:

"The fastest of all compared Forks" has been revised to "Very fast."
"Ultimate voice cloning tool" has been updated to "VITS-based Voice Conversion Tool."

2024-04-20 09:31 UTC, SleepyYui requested changes

2024-04-20 09:31 UTC, SleepyYui commented on assets/Essentials/Voice Models.md
> +- This a website where people can upload voice models.
Either This **is** a website... or just A website, This a... is not correctz

2024-04-20 09:31 UTC, SleepyYui commented on assets/Essentials/Voice Models.md
> +If you get models from different years, remember, the person's voice changes overtime.
??

2024-04-20 09:31 UTC, SleepyYui commented on assets/Essentials/Voice Models.md
> +- Click on ``Download model``. It will download a .ZIP file of it.
This will sounds better

2024-04-20 09:31 UTC, SleepyYui commented on assets/Essentials/Voice Models.md
> +If you're curious about the epochs, <u>[learn more here](https://docs.aihub.wtf/rvc/resources/epochs--tensorboard/)</u>.
you can learn more <here> is better

2024-04-20 09:31 UTC, SleepyYui commented on assets/Essentials/Voice Models.md
> +- If you need a link for it, use the other methods.
??

2024-04-20 09:31 UTC, SleepyYui commented on assets/RVC/Cloud/Applio Colab.md
> -- More unstable
37,38 have to be proven since I can neither confirm nor deny

2024-04-20 09:31 UTC, SleepyYui commented on assets/RVC/Local/Applio.md
> +- Extra features(plugins, model fusion, etc)
space and colon between features and the opening bracket

2024-04-20 09:31 UTC, SleepyYui commented on assets/RVC/Local/Applio.md
> +- Issues when downloading it in external drives
replace it in with to

2024-04-20 09:31 UTC, SleepyYui commented on assets/RVC/Local/Applio.md
> -- More unstable
once again, can't confirm nor deny

2024-04-20 09:31 UTC, SleepyYui commented on assets/RVC/Local/Applio.md
> +- Desactivate your antivirus and firewall to avoid missing dependencies.
Disable or Deactivate, Desactivate doesn't exist

2024-04-20 09:31 UTC, SleepyYui commented on assets/RVC/Local/Applio.md
> +1. Easiest way to download it is by going to their Hugging Face repo <u>[here](https://huggingface.co/IAHispano/Applio/tree/main/Compiled)</u>, and click [ :icon-download: **download** ] on the right
Replace with
```md
The easiest way to download Applio is by going to Applio's <u>[Hugging Face repo](https://huggingface.co/IAHispano/Applio/tree/main/Compiled)</u>, and clicking the [ :icon-download: **download** ] button on the right-hand side.
```

2024-04-20 09:32 UTC, SleepyYui commented
the things I cannot confirm can stay btw, I'll just ask a few people on their opinion regarding that

2024-04-20 12:17 UTC, aitronssesin commented
I'm sorry if there are a bunch of commits GitHub in mobile is horrendous

2024-04-21 09:32 UTC, SleepyYui commented
Will look at it later today, should be fine by what I've seen by now

2024-04-21 11:10 UTC, SleepyYui approved these changes
few gramar issues still but doesn't matter

2024-04-21 11:10 UTC, merged